# Generated by Django 5.1.7 on 2025-06-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='data',
            new_name='date',
        ),
    ]
